# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('interests', models.CharField(default='-', max_length=1000)),
                ('visits', models.IntegerField(default=0)),
                ('applied_date', models.DateTimeField()),
            ],
        ),
    ]
