# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170605_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(default=None, upload_to='CVs'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
