# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170606_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(default='', upload_to='CVs'),
        ),
    ]
